/*
 * Generated by gdbus-codegen 2.32.3. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "sso-auth-service-gen.h"

#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        ret = (g_value_get_double (a) == g_value_get_double (b));
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface com.google.code.AccountsSSO.gSingleSignOn.AuthService
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:SsoAuthService
 * @title: SsoAuthService
 * @short_description: Generated C code for the com.google.code.AccountsSSO.gSingleSignOn.AuthService D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-com-google-code-AccountsSSO-gSingleSignOn-AuthService.top_of_page">com.google.code.AccountsSSO.gSingleSignOn.AuthService</link> D-Bus interface in C.
 */

/* ---- Introspection data for com.google.code.AccountsSSO.gSingleSignOn.AuthService ---- */

static const _ExtendedGDBusArgInfo _sso_auth_service_method_info_register_new_identity_IN_ARG_applicationContext =
{
  {
    -1,
    "applicationContext",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _sso_auth_service_method_info_register_new_identity_IN_ARG_pointers[] =
{
  &_sso_auth_service_method_info_register_new_identity_IN_ARG_applicationContext,
  NULL
};

static const _ExtendedGDBusArgInfo _sso_auth_service_method_info_register_new_identity_OUT_ARG_objectPath =
{
  {
    -1,
    "objectPath",
    "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _sso_auth_service_method_info_register_new_identity_OUT_ARG_pointers[] =
{
  &_sso_auth_service_method_info_register_new_identity_OUT_ARG_objectPath,
  NULL
};

static const _ExtendedGDBusMethodInfo _sso_auth_service_method_info_register_new_identity =
{
  {
    -1,
    "registerNewIdentity",
    (GDBusArgInfo **) &_sso_auth_service_method_info_register_new_identity_IN_ARG_pointers,
    (GDBusArgInfo **) &_sso_auth_service_method_info_register_new_identity_OUT_ARG_pointers,
    NULL
  },
  "handle-register-new-identity",
  FALSE
};

static const _ExtendedGDBusArgInfo _sso_auth_service_method_info_get_identity_IN_ARG_id =
{
  {
    -1,
    "id",
    "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _sso_auth_service_method_info_get_identity_IN_ARG_applicationContext =
{
  {
    -1,
    "applicationContext",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _sso_auth_service_method_info_get_identity_IN_ARG_pointers[] =
{
  &_sso_auth_service_method_info_get_identity_IN_ARG_id,
  &_sso_auth_service_method_info_get_identity_IN_ARG_applicationContext,
  NULL
};

static const _ExtendedGDBusArgInfo _sso_auth_service_method_info_get_identity_OUT_ARG_objectPath =
{
  {
    -1,
    "objectPath",
    "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _sso_auth_service_method_info_get_identity_OUT_ARG_identityData =
{
  {
    -1,
    "identityData",
    "a{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _sso_auth_service_method_info_get_identity_OUT_ARG_pointers[] =
{
  &_sso_auth_service_method_info_get_identity_OUT_ARG_objectPath,
  &_sso_auth_service_method_info_get_identity_OUT_ARG_identityData,
  NULL
};

static const _ExtendedGDBusMethodInfo _sso_auth_service_method_info_get_identity =
{
  {
    -1,
    "getIdentity",
    (GDBusArgInfo **) &_sso_auth_service_method_info_get_identity_IN_ARG_pointers,
    (GDBusArgInfo **) &_sso_auth_service_method_info_get_identity_OUT_ARG_pointers,
    NULL
  },
  "handle-get-identity",
  FALSE
};

static const _ExtendedGDBusArgInfo _sso_auth_service_method_info_query_methods_OUT_ARG_authMethods =
{
  {
    -1,
    "authMethods",
    "as",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _sso_auth_service_method_info_query_methods_OUT_ARG_pointers[] =
{
  &_sso_auth_service_method_info_query_methods_OUT_ARG_authMethods,
  NULL
};

static const _ExtendedGDBusMethodInfo _sso_auth_service_method_info_query_methods =
{
  {
    -1,
    "queryMethods",
    NULL,
    (GDBusArgInfo **) &_sso_auth_service_method_info_query_methods_OUT_ARG_pointers,
    NULL
  },
  "handle-query-methods",
  FALSE
};

static const _ExtendedGDBusArgInfo _sso_auth_service_method_info_query_mechanisms_IN_ARG_method =
{
  {
    -1,
    "method",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _sso_auth_service_method_info_query_mechanisms_IN_ARG_pointers[] =
{
  &_sso_auth_service_method_info_query_mechanisms_IN_ARG_method,
  NULL
};

static const _ExtendedGDBusArgInfo _sso_auth_service_method_info_query_mechanisms_OUT_ARG_mechanisms =
{
  {
    -1,
    "mechanisms",
    "as",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _sso_auth_service_method_info_query_mechanisms_OUT_ARG_pointers[] =
{
  &_sso_auth_service_method_info_query_mechanisms_OUT_ARG_mechanisms,
  NULL
};

static const _ExtendedGDBusMethodInfo _sso_auth_service_method_info_query_mechanisms =
{
  {
    -1,
    "queryMechanisms",
    (GDBusArgInfo **) &_sso_auth_service_method_info_query_mechanisms_IN_ARG_pointers,
    (GDBusArgInfo **) &_sso_auth_service_method_info_query_mechanisms_OUT_ARG_pointers,
    NULL
  },
  "handle-query-mechanisms",
  FALSE
};

static const _ExtendedGDBusArgInfo _sso_auth_service_method_info_query_identities_IN_ARG_filter =
{
  {
    -1,
    "filter",
    "a{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _sso_auth_service_method_info_query_identities_IN_ARG_pointers[] =
{
  &_sso_auth_service_method_info_query_identities_IN_ARG_filter,
  NULL
};

static const _ExtendedGDBusArgInfo _sso_auth_service_method_info_query_identities_OUT_ARG_identities =
{
  {
    -1,
    "identities",
    "aa{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _sso_auth_service_method_info_query_identities_OUT_ARG_pointers[] =
{
  &_sso_auth_service_method_info_query_identities_OUT_ARG_identities,
  NULL
};

static const _ExtendedGDBusMethodInfo _sso_auth_service_method_info_query_identities =
{
  {
    -1,
    "queryIdentities",
    (GDBusArgInfo **) &_sso_auth_service_method_info_query_identities_IN_ARG_pointers,
    (GDBusArgInfo **) &_sso_auth_service_method_info_query_identities_OUT_ARG_pointers,
    NULL
  },
  "handle-query-identities",
  FALSE
};

static const _ExtendedGDBusArgInfo _sso_auth_service_method_info_clear_OUT_ARG_unnamed_arg0 =
{
  {
    -1,
    "unnamed_arg0",
    "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _sso_auth_service_method_info_clear_OUT_ARG_pointers[] =
{
  &_sso_auth_service_method_info_clear_OUT_ARG_unnamed_arg0,
  NULL
};

static const _ExtendedGDBusMethodInfo _sso_auth_service_method_info_clear =
{
  {
    -1,
    "clear",
    NULL,
    (GDBusArgInfo **) &_sso_auth_service_method_info_clear_OUT_ARG_pointers,
    NULL
  },
  "handle-clear",
  FALSE
};

static const _ExtendedGDBusArgInfo _sso_auth_service_method_info_backup_starts_OUT_ARG_unnamed_arg0 =
{
  {
    -1,
    "unnamed_arg0",
    "y",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _sso_auth_service_method_info_backup_starts_OUT_ARG_pointers[] =
{
  &_sso_auth_service_method_info_backup_starts_OUT_ARG_unnamed_arg0,
  NULL
};

static const _ExtendedGDBusMethodInfo _sso_auth_service_method_info_backup_starts =
{
  {
    -1,
    "backupStarts",
    NULL,
    (GDBusArgInfo **) &_sso_auth_service_method_info_backup_starts_OUT_ARG_pointers,
    NULL
  },
  "handle-backup-starts",
  FALSE
};

static const _ExtendedGDBusArgInfo _sso_auth_service_method_info_backup_finished_OUT_ARG_unnamed_arg0 =
{
  {
    -1,
    "unnamed_arg0",
    "y",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _sso_auth_service_method_info_backup_finished_OUT_ARG_pointers[] =
{
  &_sso_auth_service_method_info_backup_finished_OUT_ARG_unnamed_arg0,
  NULL
};

static const _ExtendedGDBusMethodInfo _sso_auth_service_method_info_backup_finished =
{
  {
    -1,
    "backupFinished",
    NULL,
    (GDBusArgInfo **) &_sso_auth_service_method_info_backup_finished_OUT_ARG_pointers,
    NULL
  },
  "handle-backup-finished",
  FALSE
};

static const _ExtendedGDBusArgInfo _sso_auth_service_method_info_restore_starts_OUT_ARG_unnamed_arg0 =
{
  {
    -1,
    "unnamed_arg0",
    "y",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _sso_auth_service_method_info_restore_starts_OUT_ARG_pointers[] =
{
  &_sso_auth_service_method_info_restore_starts_OUT_ARG_unnamed_arg0,
  NULL
};

static const _ExtendedGDBusMethodInfo _sso_auth_service_method_info_restore_starts =
{
  {
    -1,
    "restoreStarts",
    NULL,
    (GDBusArgInfo **) &_sso_auth_service_method_info_restore_starts_OUT_ARG_pointers,
    NULL
  },
  "handle-restore-starts",
  FALSE
};

static const _ExtendedGDBusArgInfo _sso_auth_service_method_info_restore_finished_OUT_ARG_unnamed_arg0 =
{
  {
    -1,
    "unnamed_arg0",
    "y",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _sso_auth_service_method_info_restore_finished_OUT_ARG_pointers[] =
{
  &_sso_auth_service_method_info_restore_finished_OUT_ARG_unnamed_arg0,
  NULL
};

static const _ExtendedGDBusMethodInfo _sso_auth_service_method_info_restore_finished =
{
  {
    -1,
    "restoreFinished",
    NULL,
    (GDBusArgInfo **) &_sso_auth_service_method_info_restore_finished_OUT_ARG_pointers,
    NULL
  },
  "handle-restore-finished",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _sso_auth_service_method_info_pointers[] =
{
  &_sso_auth_service_method_info_register_new_identity,
  &_sso_auth_service_method_info_get_identity,
  &_sso_auth_service_method_info_query_methods,
  &_sso_auth_service_method_info_query_mechanisms,
  &_sso_auth_service_method_info_query_identities,
  &_sso_auth_service_method_info_clear,
  &_sso_auth_service_method_info_backup_starts,
  &_sso_auth_service_method_info_backup_finished,
  &_sso_auth_service_method_info_restore_starts,
  &_sso_auth_service_method_info_restore_finished,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _sso_auth_service_interface_info =
{
  {
    -1,
    "com.google.code.AccountsSSO.gSingleSignOn.AuthService",
    (GDBusMethodInfo **) &_sso_auth_service_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "sso-auth-service",
};


/**
 * sso_auth_service_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-com-google-code-AccountsSSO-gSingleSignOn-AuthService.top_of_page">com.google.code.AccountsSSO.gSingleSignOn.AuthService</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
sso_auth_service_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_sso_auth_service_interface_info;
}

/**
 * sso_auth_service_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #SsoAuthService interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
sso_auth_service_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * SsoAuthService:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-com-google-code-AccountsSSO-gSingleSignOn-AuthService.top_of_page">com.google.code.AccountsSSO.gSingleSignOn.AuthService</link>.
 */

/**
 * SsoAuthServiceIface:
 * @parent_iface: The parent interface.
 * @handle_backup_finished: Handler for the #SsoAuthService::handle-backup-finished signal.
 * @handle_backup_starts: Handler for the #SsoAuthService::handle-backup-starts signal.
 * @handle_clear: Handler for the #SsoAuthService::handle-clear signal.
 * @handle_get_identity: Handler for the #SsoAuthService::handle-get-identity signal.
 * @handle_query_identities: Handler for the #SsoAuthService::handle-query-identities signal.
 * @handle_query_mechanisms: Handler for the #SsoAuthService::handle-query-mechanisms signal.
 * @handle_query_methods: Handler for the #SsoAuthService::handle-query-methods signal.
 * @handle_register_new_identity: Handler for the #SsoAuthService::handle-register-new-identity signal.
 * @handle_restore_finished: Handler for the #SsoAuthService::handle-restore-finished signal.
 * @handle_restore_starts: Handler for the #SsoAuthService::handle-restore-starts signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-com-google-code-AccountsSSO-gSingleSignOn-AuthService.top_of_page">com.google.code.AccountsSSO.gSingleSignOn.AuthService</link>.
 */

static void
sso_auth_service_default_init (SsoAuthServiceIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * SsoAuthService::handle-register-new-identity:
   * @object: A #SsoAuthService.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_applicationContext: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.registerNewIdentity">registerNewIdentity()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call sso_auth_service_complete_register_new_identity() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-register-new-identity",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SsoAuthServiceIface, handle_register_new_identity),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * SsoAuthService::handle-get-identity:
   * @object: A #SsoAuthService.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_id: Argument passed by remote caller.
   * @arg_applicationContext: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.getIdentity">getIdentity()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call sso_auth_service_complete_get_identity() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-identity",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SsoAuthServiceIface, handle_get_identity),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UINT, G_TYPE_STRING);

  /**
   * SsoAuthService::handle-query-methods:
   * @object: A #SsoAuthService.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.queryMethods">queryMethods()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call sso_auth_service_complete_query_methods() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-query-methods",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SsoAuthServiceIface, handle_query_methods),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * SsoAuthService::handle-query-mechanisms:
   * @object: A #SsoAuthService.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_method: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.queryMechanisms">queryMechanisms()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call sso_auth_service_complete_query_mechanisms() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-query-mechanisms",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SsoAuthServiceIface, handle_query_mechanisms),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * SsoAuthService::handle-query-identities:
   * @object: A #SsoAuthService.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_filter: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.queryIdentities">queryIdentities()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call sso_auth_service_complete_query_identities() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-query-identities",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SsoAuthServiceIface, handle_query_identities),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_VARIANT);

  /**
   * SsoAuthService::handle-clear:
   * @object: A #SsoAuthService.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.clear">clear()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call sso_auth_service_complete_clear() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-clear",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SsoAuthServiceIface, handle_clear),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * SsoAuthService::handle-backup-starts:
   * @object: A #SsoAuthService.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.backupStarts">backupStarts()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call sso_auth_service_complete_backup_starts() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-backup-starts",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SsoAuthServiceIface, handle_backup_starts),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * SsoAuthService::handle-backup-finished:
   * @object: A #SsoAuthService.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.backupFinished">backupFinished()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call sso_auth_service_complete_backup_finished() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-backup-finished",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SsoAuthServiceIface, handle_backup_finished),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * SsoAuthService::handle-restore-starts:
   * @object: A #SsoAuthService.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.restoreStarts">restoreStarts()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call sso_auth_service_complete_restore_starts() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-restore-starts",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SsoAuthServiceIface, handle_restore_starts),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * SsoAuthService::handle-restore-finished:
   * @object: A #SsoAuthService.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.restoreFinished">restoreFinished()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call sso_auth_service_complete_restore_finished() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-restore-finished",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SsoAuthServiceIface, handle_restore_finished),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

}

typedef SsoAuthServiceIface SsoAuthServiceInterface;
G_DEFINE_INTERFACE (SsoAuthService, sso_auth_service, G_TYPE_OBJECT);

/**
 * sso_auth_service_call_register_new_identity:
 * @proxy: A #SsoAuthServiceProxy.
 * @arg_applicationContext: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.registerNewIdentity">registerNewIdentity()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call sso_auth_service_call_register_new_identity_finish() to get the result of the operation.
 *
 * See sso_auth_service_call_register_new_identity_sync() for the synchronous, blocking version of this method.
 */
void
sso_auth_service_call_register_new_identity (
    SsoAuthService *proxy,
    const gchar *arg_applicationContext,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "registerNewIdentity",
    g_variant_new ("(s)",
                   arg_applicationContext),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * sso_auth_service_call_register_new_identity_finish:
 * @proxy: A #SsoAuthServiceProxy.
 * @out_objectPath: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to sso_auth_service_call_register_new_identity().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with sso_auth_service_call_register_new_identity().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sso_auth_service_call_register_new_identity_finish (
    SsoAuthService *proxy,
    gchar **out_objectPath,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_objectPath);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sso_auth_service_call_register_new_identity_sync:
 * @proxy: A #SsoAuthServiceProxy.
 * @arg_applicationContext: Argument to pass with the method invocation.
 * @out_objectPath: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.registerNewIdentity">registerNewIdentity()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See sso_auth_service_call_register_new_identity() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sso_auth_service_call_register_new_identity_sync (
    SsoAuthService *proxy,
    const gchar *arg_applicationContext,
    gchar **out_objectPath,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "registerNewIdentity",
    g_variant_new ("(s)",
                   arg_applicationContext),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_objectPath);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sso_auth_service_call_get_identity:
 * @proxy: A #SsoAuthServiceProxy.
 * @arg_id: Argument to pass with the method invocation.
 * @arg_applicationContext: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.getIdentity">getIdentity()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call sso_auth_service_call_get_identity_finish() to get the result of the operation.
 *
 * See sso_auth_service_call_get_identity_sync() for the synchronous, blocking version of this method.
 */
void
sso_auth_service_call_get_identity (
    SsoAuthService *proxy,
    guint arg_id,
    const gchar *arg_applicationContext,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "getIdentity",
    g_variant_new ("(us)",
                   arg_id,
                   arg_applicationContext),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * sso_auth_service_call_get_identity_finish:
 * @proxy: A #SsoAuthServiceProxy.
 * @out_objectPath: (out): Return location for return parameter or %NULL to ignore.
 * @out_identityData: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to sso_auth_service_call_get_identity().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with sso_auth_service_call_get_identity().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sso_auth_service_call_get_identity_finish (
    SsoAuthService *proxy,
    gchar **out_objectPath,
    GVariant **out_identityData,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o@a{sv})",
                 out_objectPath,
                 out_identityData);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sso_auth_service_call_get_identity_sync:
 * @proxy: A #SsoAuthServiceProxy.
 * @arg_id: Argument to pass with the method invocation.
 * @arg_applicationContext: Argument to pass with the method invocation.
 * @out_objectPath: (out): Return location for return parameter or %NULL to ignore.
 * @out_identityData: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.getIdentity">getIdentity()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See sso_auth_service_call_get_identity() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sso_auth_service_call_get_identity_sync (
    SsoAuthService *proxy,
    guint arg_id,
    const gchar *arg_applicationContext,
    gchar **out_objectPath,
    GVariant **out_identityData,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "getIdentity",
    g_variant_new ("(us)",
                   arg_id,
                   arg_applicationContext),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o@a{sv})",
                 out_objectPath,
                 out_identityData);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sso_auth_service_call_query_methods:
 * @proxy: A #SsoAuthServiceProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.queryMethods">queryMethods()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call sso_auth_service_call_query_methods_finish() to get the result of the operation.
 *
 * See sso_auth_service_call_query_methods_sync() for the synchronous, blocking version of this method.
 */
void
sso_auth_service_call_query_methods (
    SsoAuthService *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "queryMethods",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * sso_auth_service_call_query_methods_finish:
 * @proxy: A #SsoAuthServiceProxy.
 * @out_authMethods: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to sso_auth_service_call_query_methods().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with sso_auth_service_call_query_methods().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sso_auth_service_call_query_methods_finish (
    SsoAuthService *proxy,
    gchar ***out_authMethods,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(^as)",
                 out_authMethods);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sso_auth_service_call_query_methods_sync:
 * @proxy: A #SsoAuthServiceProxy.
 * @out_authMethods: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.queryMethods">queryMethods()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See sso_auth_service_call_query_methods() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sso_auth_service_call_query_methods_sync (
    SsoAuthService *proxy,
    gchar ***out_authMethods,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "queryMethods",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(^as)",
                 out_authMethods);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sso_auth_service_call_query_mechanisms:
 * @proxy: A #SsoAuthServiceProxy.
 * @arg_method: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.queryMechanisms">queryMechanisms()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call sso_auth_service_call_query_mechanisms_finish() to get the result of the operation.
 *
 * See sso_auth_service_call_query_mechanisms_sync() for the synchronous, blocking version of this method.
 */
void
sso_auth_service_call_query_mechanisms (
    SsoAuthService *proxy,
    const gchar *arg_method,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "queryMechanisms",
    g_variant_new ("(s)",
                   arg_method),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * sso_auth_service_call_query_mechanisms_finish:
 * @proxy: A #SsoAuthServiceProxy.
 * @out_mechanisms: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to sso_auth_service_call_query_mechanisms().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with sso_auth_service_call_query_mechanisms().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sso_auth_service_call_query_mechanisms_finish (
    SsoAuthService *proxy,
    gchar ***out_mechanisms,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(^as)",
                 out_mechanisms);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sso_auth_service_call_query_mechanisms_sync:
 * @proxy: A #SsoAuthServiceProxy.
 * @arg_method: Argument to pass with the method invocation.
 * @out_mechanisms: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.queryMechanisms">queryMechanisms()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See sso_auth_service_call_query_mechanisms() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sso_auth_service_call_query_mechanisms_sync (
    SsoAuthService *proxy,
    const gchar *arg_method,
    gchar ***out_mechanisms,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "queryMechanisms",
    g_variant_new ("(s)",
                   arg_method),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(^as)",
                 out_mechanisms);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sso_auth_service_call_query_identities:
 * @proxy: A #SsoAuthServiceProxy.
 * @arg_filter: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.queryIdentities">queryIdentities()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call sso_auth_service_call_query_identities_finish() to get the result of the operation.
 *
 * See sso_auth_service_call_query_identities_sync() for the synchronous, blocking version of this method.
 */
void
sso_auth_service_call_query_identities (
    SsoAuthService *proxy,
    GVariant *arg_filter,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "queryIdentities",
    g_variant_new ("(@a{sv})",
                   arg_filter),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * sso_auth_service_call_query_identities_finish:
 * @proxy: A #SsoAuthServiceProxy.
 * @out_identities: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to sso_auth_service_call_query_identities().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with sso_auth_service_call_query_identities().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sso_auth_service_call_query_identities_finish (
    SsoAuthService *proxy,
    GVariant **out_identities,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@aa{sv})",
                 out_identities);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sso_auth_service_call_query_identities_sync:
 * @proxy: A #SsoAuthServiceProxy.
 * @arg_filter: Argument to pass with the method invocation.
 * @out_identities: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.queryIdentities">queryIdentities()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See sso_auth_service_call_query_identities() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sso_auth_service_call_query_identities_sync (
    SsoAuthService *proxy,
    GVariant *arg_filter,
    GVariant **out_identities,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "queryIdentities",
    g_variant_new ("(@a{sv})",
                   arg_filter),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@aa{sv})",
                 out_identities);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sso_auth_service_call_clear:
 * @proxy: A #SsoAuthServiceProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.clear">clear()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call sso_auth_service_call_clear_finish() to get the result of the operation.
 *
 * See sso_auth_service_call_clear_sync() for the synchronous, blocking version of this method.
 */
void
sso_auth_service_call_clear (
    SsoAuthService *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "clear",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * sso_auth_service_call_clear_finish:
 * @proxy: A #SsoAuthServiceProxy.
 * @out_unnamed_arg0: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to sso_auth_service_call_clear().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with sso_auth_service_call_clear().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sso_auth_service_call_clear_finish (
    SsoAuthService *proxy,
    gboolean *out_unnamed_arg0,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_unnamed_arg0);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sso_auth_service_call_clear_sync:
 * @proxy: A #SsoAuthServiceProxy.
 * @out_unnamed_arg0: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.clear">clear()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See sso_auth_service_call_clear() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sso_auth_service_call_clear_sync (
    SsoAuthService *proxy,
    gboolean *out_unnamed_arg0,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "clear",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_unnamed_arg0);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sso_auth_service_call_backup_starts:
 * @proxy: A #SsoAuthServiceProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.backupStarts">backupStarts()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call sso_auth_service_call_backup_starts_finish() to get the result of the operation.
 *
 * See sso_auth_service_call_backup_starts_sync() for the synchronous, blocking version of this method.
 */
void
sso_auth_service_call_backup_starts (
    SsoAuthService *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "backupStarts",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * sso_auth_service_call_backup_starts_finish:
 * @proxy: A #SsoAuthServiceProxy.
 * @out_unnamed_arg0: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to sso_auth_service_call_backup_starts().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with sso_auth_service_call_backup_starts().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sso_auth_service_call_backup_starts_finish (
    SsoAuthService *proxy,
    guchar *out_unnamed_arg0,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(y)",
                 out_unnamed_arg0);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sso_auth_service_call_backup_starts_sync:
 * @proxy: A #SsoAuthServiceProxy.
 * @out_unnamed_arg0: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.backupStarts">backupStarts()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See sso_auth_service_call_backup_starts() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sso_auth_service_call_backup_starts_sync (
    SsoAuthService *proxy,
    guchar *out_unnamed_arg0,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "backupStarts",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(y)",
                 out_unnamed_arg0);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sso_auth_service_call_backup_finished:
 * @proxy: A #SsoAuthServiceProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.backupFinished">backupFinished()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call sso_auth_service_call_backup_finished_finish() to get the result of the operation.
 *
 * See sso_auth_service_call_backup_finished_sync() for the synchronous, blocking version of this method.
 */
void
sso_auth_service_call_backup_finished (
    SsoAuthService *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "backupFinished",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * sso_auth_service_call_backup_finished_finish:
 * @proxy: A #SsoAuthServiceProxy.
 * @out_unnamed_arg0: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to sso_auth_service_call_backup_finished().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with sso_auth_service_call_backup_finished().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sso_auth_service_call_backup_finished_finish (
    SsoAuthService *proxy,
    guchar *out_unnamed_arg0,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(y)",
                 out_unnamed_arg0);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sso_auth_service_call_backup_finished_sync:
 * @proxy: A #SsoAuthServiceProxy.
 * @out_unnamed_arg0: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.backupFinished">backupFinished()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See sso_auth_service_call_backup_finished() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sso_auth_service_call_backup_finished_sync (
    SsoAuthService *proxy,
    guchar *out_unnamed_arg0,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "backupFinished",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(y)",
                 out_unnamed_arg0);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sso_auth_service_call_restore_starts:
 * @proxy: A #SsoAuthServiceProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.restoreStarts">restoreStarts()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call sso_auth_service_call_restore_starts_finish() to get the result of the operation.
 *
 * See sso_auth_service_call_restore_starts_sync() for the synchronous, blocking version of this method.
 */
void
sso_auth_service_call_restore_starts (
    SsoAuthService *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "restoreStarts",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * sso_auth_service_call_restore_starts_finish:
 * @proxy: A #SsoAuthServiceProxy.
 * @out_unnamed_arg0: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to sso_auth_service_call_restore_starts().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with sso_auth_service_call_restore_starts().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sso_auth_service_call_restore_starts_finish (
    SsoAuthService *proxy,
    guchar *out_unnamed_arg0,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(y)",
                 out_unnamed_arg0);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sso_auth_service_call_restore_starts_sync:
 * @proxy: A #SsoAuthServiceProxy.
 * @out_unnamed_arg0: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.restoreStarts">restoreStarts()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See sso_auth_service_call_restore_starts() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sso_auth_service_call_restore_starts_sync (
    SsoAuthService *proxy,
    guchar *out_unnamed_arg0,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "restoreStarts",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(y)",
                 out_unnamed_arg0);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sso_auth_service_call_restore_finished:
 * @proxy: A #SsoAuthServiceProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.restoreFinished">restoreFinished()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call sso_auth_service_call_restore_finished_finish() to get the result of the operation.
 *
 * See sso_auth_service_call_restore_finished_sync() for the synchronous, blocking version of this method.
 */
void
sso_auth_service_call_restore_finished (
    SsoAuthService *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "restoreFinished",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * sso_auth_service_call_restore_finished_finish:
 * @proxy: A #SsoAuthServiceProxy.
 * @out_unnamed_arg0: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to sso_auth_service_call_restore_finished().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with sso_auth_service_call_restore_finished().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sso_auth_service_call_restore_finished_finish (
    SsoAuthService *proxy,
    guchar *out_unnamed_arg0,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(y)",
                 out_unnamed_arg0);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sso_auth_service_call_restore_finished_sync:
 * @proxy: A #SsoAuthServiceProxy.
 * @out_unnamed_arg0: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.restoreFinished">restoreFinished()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See sso_auth_service_call_restore_finished() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sso_auth_service_call_restore_finished_sync (
    SsoAuthService *proxy,
    guchar *out_unnamed_arg0,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "restoreFinished",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(y)",
                 out_unnamed_arg0);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sso_auth_service_complete_register_new_identity:
 * @object: A #SsoAuthService.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @objectPath: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.registerNewIdentity">registerNewIdentity()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
sso_auth_service_complete_register_new_identity (
    SsoAuthService *object,
    GDBusMethodInvocation *invocation,
    const gchar *objectPath)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(o)",
                   objectPath));
}

/**
 * sso_auth_service_complete_get_identity:
 * @object: A #SsoAuthService.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @objectPath: Parameter to return.
 * @identityData: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.getIdentity">getIdentity()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
sso_auth_service_complete_get_identity (
    SsoAuthService *object,
    GDBusMethodInvocation *invocation,
    const gchar *objectPath,
    GVariant *identityData)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(o@a{sv})",
                   objectPath,
                   identityData));
}

/**
 * sso_auth_service_complete_query_methods:
 * @object: A #SsoAuthService.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @authMethods: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.queryMethods">queryMethods()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
sso_auth_service_complete_query_methods (
    SsoAuthService *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *authMethods)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(^as)",
                   authMethods));
}

/**
 * sso_auth_service_complete_query_mechanisms:
 * @object: A #SsoAuthService.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @mechanisms: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.queryMechanisms">queryMechanisms()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
sso_auth_service_complete_query_mechanisms (
    SsoAuthService *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *mechanisms)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(^as)",
                   mechanisms));
}

/**
 * sso_auth_service_complete_query_identities:
 * @object: A #SsoAuthService.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @identities: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.queryIdentities">queryIdentities()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
sso_auth_service_complete_query_identities (
    SsoAuthService *object,
    GDBusMethodInvocation *invocation,
    GVariant *identities)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(@aa{sv})",
                   identities));
}

/**
 * sso_auth_service_complete_clear:
 * @object: A #SsoAuthService.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @unnamed_arg0: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.clear">clear()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
sso_auth_service_complete_clear (
    SsoAuthService *object,
    GDBusMethodInvocation *invocation,
    gboolean unnamed_arg0)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   unnamed_arg0));
}

/**
 * sso_auth_service_complete_backup_starts:
 * @object: A #SsoAuthService.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @unnamed_arg0: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.backupStarts">backupStarts()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
sso_auth_service_complete_backup_starts (
    SsoAuthService *object,
    GDBusMethodInvocation *invocation,
    guchar unnamed_arg0)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(y)",
                   unnamed_arg0));
}

/**
 * sso_auth_service_complete_backup_finished:
 * @object: A #SsoAuthService.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @unnamed_arg0: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.backupFinished">backupFinished()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
sso_auth_service_complete_backup_finished (
    SsoAuthService *object,
    GDBusMethodInvocation *invocation,
    guchar unnamed_arg0)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(y)",
                   unnamed_arg0));
}

/**
 * sso_auth_service_complete_restore_starts:
 * @object: A #SsoAuthService.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @unnamed_arg0: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.restoreStarts">restoreStarts()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
sso_auth_service_complete_restore_starts (
    SsoAuthService *object,
    GDBusMethodInvocation *invocation,
    guchar unnamed_arg0)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(y)",
                   unnamed_arg0));
}

/**
 * sso_auth_service_complete_restore_finished:
 * @object: A #SsoAuthService.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @unnamed_arg0: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-google-code-AccountsSSO-gSingleSignOn-AuthService.restoreFinished">restoreFinished()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
sso_auth_service_complete_restore_finished (
    SsoAuthService *object,
    GDBusMethodInvocation *invocation,
    guchar unnamed_arg0)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(y)",
                   unnamed_arg0));
}

/* ------------------------------------------------------------------------ */

/**
 * SsoAuthServiceProxy:
 *
 * The #SsoAuthServiceProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * SsoAuthServiceProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #SsoAuthServiceProxy.
 */

struct _SsoAuthServiceProxyPrivate
{
  GData *qdata;
};

static void sso_auth_service_proxy_iface_init (SsoAuthServiceIface *iface);

G_DEFINE_TYPE_WITH_CODE (SsoAuthServiceProxy, sso_auth_service_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_SSO_AUTH_SERVICE, sso_auth_service_proxy_iface_init));

static void
sso_auth_service_proxy_finalize (GObject *object)
{
  SsoAuthServiceProxy *proxy = SSO_AUTH_SERVICE_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (sso_auth_service_proxy_parent_class)->finalize (object);
}

static void
sso_auth_service_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
}

static void
sso_auth_service_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
}

static void
sso_auth_service_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_sso_auth_service_interface_info, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TYPE_SSO_AUTH_SERVICE);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_SSO_AUTH_SERVICE);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
sso_auth_service_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  SsoAuthServiceProxy *proxy = SSO_AUTH_SERVICE_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_sso_auth_service_interface_info, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_sso_auth_service_interface_info, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
sso_auth_service_proxy_init (SsoAuthServiceProxy *proxy)
{
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, TYPE_SSO_AUTH_SERVICE_PROXY, SsoAuthServiceProxyPrivate);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), sso_auth_service_interface_info ());
}

static void
sso_auth_service_proxy_class_init (SsoAuthServiceProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  g_type_class_add_private (klass, sizeof (SsoAuthServiceProxyPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = sso_auth_service_proxy_finalize;
  gobject_class->get_property = sso_auth_service_proxy_get_property;
  gobject_class->set_property = sso_auth_service_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = sso_auth_service_proxy_g_signal;
  proxy_class->g_properties_changed = sso_auth_service_proxy_g_properties_changed;

}

static void
sso_auth_service_proxy_iface_init (SsoAuthServiceIface *iface)
{
}

/**
 * sso_auth_service_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-google-code-AccountsSSO-gSingleSignOn-AuthService.top_of_page">com.google.code.AccountsSSO.gSingleSignOn.AuthService</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call sso_auth_service_proxy_new_finish() to get the result of the operation.
 *
 * See sso_auth_service_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
sso_auth_service_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_SSO_AUTH_SERVICE_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.google.code.AccountsSSO.gSingleSignOn.AuthService", NULL);
}

/**
 * sso_auth_service_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to sso_auth_service_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with sso_auth_service_proxy_new().
 *
 * Returns: (transfer full) (type SsoAuthServiceProxy): The constructed proxy object or %NULL if @error is set.
 */
SsoAuthService *
sso_auth_service_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return SSO_AUTH_SERVICE (ret);
  else
    return NULL;
}

/**
 * sso_auth_service_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-google-code-AccountsSSO-gSingleSignOn-AuthService.top_of_page">com.google.code.AccountsSSO.gSingleSignOn.AuthService</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See sso_auth_service_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type SsoAuthServiceProxy): The constructed proxy object or %NULL if @error is set.
 */
SsoAuthService *
sso_auth_service_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_SSO_AUTH_SERVICE_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.google.code.AccountsSSO.gSingleSignOn.AuthService", NULL);
  if (ret != NULL)
    return SSO_AUTH_SERVICE (ret);
  else
    return NULL;
}


/**
 * sso_auth_service_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like sso_auth_service_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call sso_auth_service_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See sso_auth_service_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
sso_auth_service_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_SSO_AUTH_SERVICE_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.google.code.AccountsSSO.gSingleSignOn.AuthService", NULL);
}

/**
 * sso_auth_service_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to sso_auth_service_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with sso_auth_service_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type SsoAuthServiceProxy): The constructed proxy object or %NULL if @error is set.
 */
SsoAuthService *
sso_auth_service_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return SSO_AUTH_SERVICE (ret);
  else
    return NULL;
}

/**
 * sso_auth_service_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like sso_auth_service_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See sso_auth_service_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type SsoAuthServiceProxy): The constructed proxy object or %NULL if @error is set.
 */
SsoAuthService *
sso_auth_service_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_SSO_AUTH_SERVICE_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.google.code.AccountsSSO.gSingleSignOn.AuthService", NULL);
  if (ret != NULL)
    return SSO_AUTH_SERVICE (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * SsoAuthServiceSkeleton:
 *
 * The #SsoAuthServiceSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * SsoAuthServiceSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #SsoAuthServiceSkeleton.
 */

struct _SsoAuthServiceSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_sso_auth_service_skeleton_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  SsoAuthServiceSkeleton *skeleton = SSO_AUTH_SERVICE_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TYPE_SSO_AUTH_SERVICE);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_SSO_AUTH_SERVICE);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_sso_auth_service_skeleton_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  SsoAuthServiceSkeleton *skeleton = SSO_AUTH_SERVICE_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_sso_auth_service_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_sso_auth_service_skeleton_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  SsoAuthServiceSkeleton *skeleton = SSO_AUTH_SERVICE_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_sso_auth_service_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _sso_auth_service_skeleton_vtable =
{
  _sso_auth_service_skeleton_handle_method_call,
  _sso_auth_service_skeleton_handle_get_property,
  _sso_auth_service_skeleton_handle_set_property
};

static GDBusInterfaceInfo *
sso_auth_service_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton)
{
  return sso_auth_service_interface_info ();
}

static GDBusInterfaceVTable *
sso_auth_service_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton)
{
  return (GDBusInterfaceVTable *) &_sso_auth_service_skeleton_vtable;
}

static GVariant *
sso_auth_service_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  SsoAuthServiceSkeleton *skeleton = SSO_AUTH_SERVICE_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_sso_auth_service_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _sso_auth_service_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _sso_auth_service_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _sso_auth_service_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.google.code.AccountsSSO.gSingleSignOn.AuthService", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
sso_auth_service_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void sso_auth_service_skeleton_iface_init (SsoAuthServiceIface *iface);
G_DEFINE_TYPE_WITH_CODE (SsoAuthServiceSkeleton, sso_auth_service_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TYPE_SSO_AUTH_SERVICE, sso_auth_service_skeleton_iface_init));

static void
sso_auth_service_skeleton_finalize (GObject *object)
{
  SsoAuthServiceSkeleton *skeleton = SSO_AUTH_SERVICE_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (sso_auth_service_skeleton_parent_class)->finalize (object);
}

static void
sso_auth_service_skeleton_init (SsoAuthServiceSkeleton *skeleton)
{
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TYPE_SSO_AUTH_SERVICE_SKELETON, SsoAuthServiceSkeletonPrivate);
  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
sso_auth_service_skeleton_class_init (SsoAuthServiceSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  g_type_class_add_private (klass, sizeof (SsoAuthServiceSkeletonPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = sso_auth_service_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = sso_auth_service_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = sso_auth_service_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = sso_auth_service_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = sso_auth_service_skeleton_dbus_interface_get_vtable;
}

static void
sso_auth_service_skeleton_iface_init (SsoAuthServiceIface *iface)
{
}

/**
 * sso_auth_service_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-com-google-code-AccountsSSO-gSingleSignOn-AuthService.top_of_page">com.google.code.AccountsSSO.gSingleSignOn.AuthService</link>.
 *
 * Returns: (transfer full) (type SsoAuthServiceSkeleton): The skeleton object.
 */
SsoAuthService *
sso_auth_service_skeleton_new (void)
{
  return SSO_AUTH_SERVICE (g_object_new (TYPE_SSO_AUTH_SERVICE_SKELETON, NULL));
}

